pcp_test_node:
  # 传感器参数
  max_sensor_range: 5.0
  min_sensor_range: 0.5
  voxel_grid_size: 0.01
  statistical_filter_mean_k: 12
  statistical_filter_std_dev: 0.3
  lidar_frame_id: "livox_frame"
  body_frame_id: "base_link"
  lidar_topic: "/livox/lidar"

  # 直方图参数
  azimuth_resolution_deg: 10.0  # 方位角步长（度）
  elevation_resolution_deg: 5.0  # 俯仰角步长（度）
  min_azimuth_deg: -180.0  # 最小方位角
  max_azimuth_deg: 180.0  # 最大方位角
  min_elevation_deg: -7.0  # 最小俯仰角
  max_elevation_deg: 53.0  # 最大俯仰角
